import Head from 'next/head'
import Link from 'next/link'
import { useQuery } from 'urql';
import Product from '../components/Products';
import { PRODUCT_QUERY } from '../lib/query';
import { GalleryStyle } from '../styles/Gallery';
import Nav from '../components/Nav';

export default function Home() {
  //Fetch products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //Check for the data coming in
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no! {error.message}</p>;
  const products = data.products.data;

  return (
    <div >
      <Head>
        <title>Styled Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GalleryStyle>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </GalleryStyle>
      </main>
    </div>
  )
}
